cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_cart, name='show_cart'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('delete_from_main_cart/', views.delete_from_main_cart, name='delete_from_main_cart'),
    path('use_promo/', views.use_promo, name='use_promo'),
    path('sort_filter/', views.sort_filter, name='sort_filter'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('delete_from_cart/', views.delete_from_cart, name='delete_from_cart'),
    path('wishlist_add/', views.wishlist_add, name='wishlist_add'),
    path('wishlist_delete/', views.wishlist_delete, name='wishlist_delete'),
    path('get_cart/', views.get_cart, name='get_cart'),
    path('add_to_fav/', views.add_to_fav, name='add_to_fav'),



    # path('login/', views.login, name='login'),
    # path('logout/', views.logout_page, name='logout'),
    # path('profile/<nickname_req>', views.profile, name='profile'),
    # path('del_message/', views.del_message, name='del_message'),
    # path('bonus_pack/', views.bonus_pack, name='bonus_pack'),
    # path('about_us/', views.about_us, name='about_us'),
    # path('rules/', views.rules, name='rules'),
    # path('add_to_player_balance/', views.add_to_player_balance, name='add_to_player_balance'),
    # path('about_bonus_pack/', views.about_bonus_pack, name='about_bonus_pack'),




    # path('statistic/', views.statistic, name='statistic'),

]

item/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('quick_view/', views.quick_view, name='quick_view'),
    path('<item_slug>/', views.item_page, name='item_page'),




    # path('login/', views.login, name='login'),
    # path('logout/', views.logout_page, name='logout'),
    # path('profile/<nickname_req>', views.profile, name='profile'),
    # path('del_message/', views.del_message, name='del_message'),
    # path('bonus_pack/', views.bonus_pack, name='bonus_pack'),
    # path('about_us/', views.about_us, name='about_us'),
    # path('rules/', views.rules, name='rules'),
    # path('add_to_player_balance/', views.add_to_player_balance, name='add_to_player_balance'),
    # path('about_bonus_pack/', views.about_bonus_pack, name='about_bonus_pack'),




    # path('statistic/', views.statistic, name='statistic'),

]

laskshmi_vue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# from page.views import customhandler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('item/', include('item.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('customuser.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from customuser.models import User, Guest
from item.models import Item

class Cart(models.Model):
    client = models.ForeignKey(User, blank=True, null=True, default=None, on_delete=models.CASCADE,
                               verbose_name='Корзина клиента')
    guest = models.ForeignKey(Guest, blank=True, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='Корзина гостя')
    item = models.ForeignKey(Item, blank=True, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='Товар')
    number = models.IntegerField('Кол-во', blank=True, null=True, default=0)
    current_price = models.IntegerField('Цена за ед.', default=0)
    total_price = models.IntegerField('Общая стоимость', default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        if self.client:
            return 'Товар в корзине клиента : %s ' % self.client.name
        elif self.guest:
            return 'Товар в корзине гостя : %s ' % self.guest.id
        else:
            return 'Товар в корзине'

    class Meta:
        verbose_name = "Товар в корзине"
        verbose_name_plural = "Товары в корзинах"

    def save(self, *args, **kwargs):
        if self.item.discount > 0:
            self.current_price = self.item.price - (self.item.price * self.item.discount / 100)
        else:
            self.current_price = self.item.price
        self.total_price = self.number * self.current_price

        super(Cart, self).save(*args, **kwargs)

item/models.py
from django.db import models
from django.utils import timezone
from pytils.translit import slugify
from PIL import Image
from django.db.models.signals import post_save
import uuid
from random import choices
import string
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from django.utils.safestring import mark_safe
#from laskshmi import settings

import os


def format_number(num):
    if num % 1 == 0:
        return int(num)
    else:
        return num

class Category(models.Model):
    name = models.CharField('Название категории', max_length=255, blank=False, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField('Изображение категории', upload_to='category_img/', blank=False)
    icon = models.ImageField('Иконка категории', upload_to='category_img/', blank=True,null=True)
    page_title = models.CharField('Название страницы', max_length=255, blank=False, null=True)
    page_description = models.CharField('Описание страницы', max_length=255, blank=False, null=True)
    page_keywords = models.TextField('Keywords', blank=False, null=True)
    short_description = models.TextField('Краткое описание для главной', blank=True,)
    description = RichTextUploadingField('Описание категории', blank=True, null=True)
    views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return 'id :%s , %s ' % (self.id, self.name)

    def get_icon(self):
        if self.icon:
            return self.icon.url
        else:
            return 'https://placehold.it/40'

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class SubCategory(models.Model):
    category = models.ForeignKey(Category, blank=False, null=True, on_delete=models.SET_NULL)
    name = models.CharField('Название подкатегории', max_length=255, blank=False, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)
    icon = models.ImageField('Иконка категории', upload_to='category_img/', blank=True, null=True)
    image = models.ImageField('Изображение подкатегории', upload_to='sub_category_img/', blank=False)
    page_title = models.CharField('Название страницы', max_length=255, blank=False, null=True)
    page_description = models.CharField('Описание страницы', max_length=255, blank=False, null=True)
    page_keywords = models.TextField('Keywords', blank=False, null=True)
    description = RichTextUploadingField('Описание подкатегории', blank=True, null=True)
    discount = models.IntegerField('Скидка на все товары в подкатегории %', blank=True, default=0)
    views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        all_items = self.item_set.all()
        for item in all_items:
            item.discount = self.discount
            item.save()

        super(SubCategory, self).save(*args, **kwargs)

    def __str__(self):
        return 'id :%s , %s ' % (self.id, self.name)

    class Meta:
        verbose_name = "Подкатегория"
        verbose_name_plural = "Подкатегории"


class Filter(models.Model):
    subcategory = models.ForeignKey(SubCategory, blank=True, null=True,on_delete=models.SET_NULL, verbose_name='Подкатегория')
    name = models.CharField('Название фильтра', max_length=255, blank=False, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)
    seoText = RichTextUploadingField('Текст для СЕО', blank=True, null=True)

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        super(Filter, self).save(*args, **kwargs)

    def __str__(self):
        return '%s | %s ' % (self.subcategory.name, self.name)

    class Meta:
        verbose_name = "Фильтр"
        verbose_name_plural = "Фильтры"

class Star(models.Model):
    name = models.CharField('Название звезды', max_length=255, blank=False, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)
    seoText = RichTextUploadingField('Текст для СЕО', blank=True, null=True)

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        super(Star, self).save(*args, **kwargs)

    def __str__(self):
        return f'Звезда {self.name} '

    class Meta:
        verbose_name = "Звезда"
        verbose_name_plural = "Звезды"

class Collection(models.Model):
    category = models.ForeignKey(Category, blank=False, null=True, on_delete=models.SET_NULL, verbose_name='Категория')
    name = models.CharField('Название коллекции', max_length=255, blank=False, null=True)
    icon = models.ImageField('Иконка категории', upload_to='category_img/', blank=True, null=True)
    name_slug = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField('Изображение коллекции', upload_to='collection_img/', blank=False)
    page_title = models.CharField('Название страницы', max_length=255, blank=False, null=True)
    page_description = models.TextField('Описание страницы', blank=False, null=True)
    page_keywords = models.TextField('Keywords', blank=False, null=True)
    description = RichTextUploadingField('Описание коллекции', blank=True, null=True)
    discount = models.IntegerField('Скидка на все товары в коллекции %', blank=True, default=0)
    views = models.IntegerField(default=0)
    show_at_homepage = models.BooleanField('Отображать на главной', default=True)
    show_at_category = models.BooleanField('Отображать в категории', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_special = models.BooleanField('Спец. коллекция', default=False)

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        all_items = Item.objects.filter(collection=self)
        for item in all_items:
            item.discount = self.discount
            item.save()
        super(Collection, self).save(*args, **kwargs)

    def get_icon(self):
        if self.icon:
            return self.icon.url
        else:
            return 'https://placehold.it/40'

    def __str__(self):
        return '%s ' % self.name

    class Meta:
        verbose_name = "Коллекция"
        verbose_name_plural = "Коллекции"

class Item(models.Model):
    collection = models.ManyToManyField(Collection, blank=True, verbose_name='Коллекция',db_index=True)
    filter = models.ForeignKey(Filter, blank=True, null=True, on_delete=models.SET_NULL,db_index=True)
    star = models.ForeignKey(Star, blank=True, null=True, on_delete=models.SET_NULL,db_index=True)
    subcategory = models.ForeignKey(SubCategory, blank=False, null=True, verbose_name='Подкатегория', on_delete=models.SET_NULL,db_index=True)
    name = models.CharField('Название товара', max_length=255, blank=False, null=True)
    name_lower = models.CharField(max_length=255, blank=True, null=True,default='')
    name_slug = models.CharField(max_length=255, blank=True, null=True,db_index=True)
    price = models.IntegerField('Цена', blank=False, default=0, db_index=True)
    discount = models.IntegerField('Скидка %', blank=True, default=0, db_index=True)
    page_title = models.CharField('Название страницы', max_length=255, blank=False, null=True)
    page_description = models.TextField('Описание страницы',  blank=False, null=True)
    description = models.TextField('Описание товара', blank=True, null=True)
    comment = models.TextField('Комментарий', blank=True, null=True)
    length = models.CharField('Длина', max_length=15, default='не указано')
    width = models.CharField('Ширина', max_length=15, default='не указано')
    height = models.CharField('Высота',  max_length=15, default='не указано')
    article = models.CharField('Артикул', max_length=50, blank=False, null=True)
    weight = models.CharField('Вес',  max_length=15, default='не указано')
    material = models.CharField('Материал', max_length=50, blank=True, null=True, default='не указано')
    is_active = models.BooleanField('Отображать товар ?', default=True, db_index=True)
    is_present = models.BooleanField('Товар в наличии ?', default=True, db_index=True)
    is_new = models.BooleanField('Товар новинка ?', default=False, db_index=True)
    is_reserved = models.BooleanField('Товар в резерве ?', default=False)
    buys = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.name_slug = slugify(self.name)
        self.name_lower = self.name.lower()
        super(Item, self).save(*args, **kwargs)

    def getfirstimage(self):
        url = None
        for img in self.itemimage_set.all():
            if img.is_main:
                url = img.image_small
        return url

    def image_tag(self):
        # used in the admin site model as a "thumbnail"
        if self.getfirstimage():
            return mark_safe('<img src="{}" width="100" height="100" />'.format(self.getfirstimage()))
        else:
            return mark_safe('<span>НЕТ МИНИАТЮРЫ</span>')

    image_tag.short_description = 'Основная картинка'



    @property
    def discount_value(self):
        if self.discount > 0:
            dis_val = self.price - (self.price * self.discount / 100)
        else:
            dis_val = self.price
        return (round(dis_val))


    def __str__(self):
        if self.filter:
            return 'id:%s %s | Фильтр %s' % (self.id, self.name, self.filter.name)
        else:

item/views.py
import json

from django.shortcuts import render
from django.http import JsonResponse, Http404
from item.models import Item,ItemImage
from order.models import Wishlist
from cart.models import Cart
from customuser.models import User, Guest

def quick_view(request):
    return_dict = {}
    data = request.POST
    print(data)
    item_id = int(data.get('item_id'))
    item = Item.objects.get(id=item_id)
    images = ItemImage.objects.filter(item_id=item_id)
    if item.discount > 0:
        return_dict['item_price_discount'] = item.discount_value
    return_dict['item_id'] = item.id
    return_dict['item_name'] = item.name
    return_dict['item_name_slug'] = item.name_slug
    return_dict['item_description'] = item.description
    return_dict['item_price'] = item.price
    return_dict['item_discount'] = item.discount
    return_dict['item_new'] = item.is_new
    return_dict['item_article'] = item.article
    return_dict['item_present'] = item.is_present
    return_dict['item_images'] = list()
    for image in images:
        return_dict['item_images'].append(image.image_small)
    return JsonResponse(return_dict)




def item_page(request, item_slug):
    print(request.get_host())
    try:
        item = Item.objects.get(name_slug=item_slug)
        item.views += 1
        item.save(force_update=True)
        recomended = Item.objects.filter(subcategory_id=item.subcategory_id).order_by('-views')[:12]
        # title = item.name
        # description = item.description

        print(recomended)
    except:
        raise Http404
        # return render(request, '404.html', locals())
    title = '{} | артикул {} - купить оптом в Москве'.format(item.name, item.article)
    description = 'Заказывайте оптом {} (артикул {}) в интернет-магазине ЛАКШМИ.' \
                  ' Большой выбор товаров на различную тематику по доступным ценам. Доставка по России.'.format(item.name, item.article)
    return render(request, 'page/item.html', locals())

templates/page/about_us.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}
<div class="main">
    <div class="container">
        <div class="breadcrumbs">
            <ul>
                <li><a href="#">Главная</a></li>

                <li>Доставка</li>
            </ul>
        </div>

    </div>
    <section class="contact">
        <div class="container">
            <div class="section-header"><h1>Информация о доставке</h1></div>
            <div class="info-blocks">

                <div class="info-blocks__item block-w-r4" >
                    <img class="mb-30" src="images/yin-yang_icon.png" alt="">
                    <p class="text-bold mb-20">САМОВЫВОЗ</p>
                    <p class="mb-40">Вы можете забрать ваш заказ сами с нашего склада по адресу:<br>
                        г. Москва, метро Нагорная, Электорлитный проезд, дом 10, склад 18</p>
                    <p class="text-bold">Стоимость: бесплатно</p>
                </div>
                <div class="info-blocks__item block-w-r4">
                    <img class="mb-30" src="images/yin-yang_icon.png" alt="">
                    <p class="text-bold mb-20">ДОСТАВКА КУРЬЕРОМ</p>
                    <p class="mb-40">Мы доставляем заказы курьером по Москве
                        (в пределах МКАД). По поводу доставки
                        за пределы МКАД - звоните по контактному номеру:
                        +7 (495) 926 33 59</p>
                    <p class="text-bold">Стоимость: 500 рублей</p>
                </div>
                <div class="info-blocks__item block-w-r4">
                    <img class="mb-30" src="images/yin-yang_icon.png" alt="">
                    <p class="text-bold mb-20">ДОСТАВКА ТРАНСПОРТНОЙ КОМПАНИЕЙ</p>
                    <p class="mb-20">Мы отправляем грузы по всей территории РФ! Со списком ТК вы можете ознакомиться ниже.
                        Стоимость доставки груза до вашего города уточняйте индивидуально у ТК!
                        Ниже указана стоимость доставки груза до ТК</p>
                    <p class="text-bold"> Стоимость: 500 рублей (при заказе от 5.000 - бесплатно)</p>
                </div>

            </div>
            <div class="section-header">
                <h4 >Список транспортных компаний</h4>
                <div class="hr"></div>
            </div>
            <div class="block-w-r4">
                <p class="text-bold">
                    ТК "РАТЭК"<br>
                    ТК «Мейджик Транс»<br>
                    ТК «Байкал-Сервис»<br>
                    ТК «ФАСТранс»<br>
                    ТК «Экспресс-Авто»<br>
                    ТК «ЖелДорЭкспедиция»<br>
                    ТК «Деловые Линии»<br>
                    ТК "Почтовая Экспедиционная Компания"<br>
                    ТК "ПЭК"<br>
                    СДЭК<br>
                    ТК "Деливери"<br>
                    ТК «КИТ»<br>
                </p>

            </div>
        </div>
    </section>

</div>
{% endblock %}

templates/page/checkout.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}
    {% if total_cart_price %}
        {% if request.user.is_authenticated %}
            {% include 'page/checkout_members.html' %}
        {% else %}
            {% include 'page/checkout_guest.html' %}
        {% endif %}
    {% else %}
         {% include 'page/empty_cart.html' %}
    {% endif %}





{% endblock %}

templates/page/subcategory.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}

    <div class="main">
        <div class="container">
            <div class="breadcrumbs">
                <ul>
                    <li><a href="/">Главная</a></li>
                    <li><a href="{% url 'category' subcat.category.name_slug %}">{{ subcat.category.name.upper }}</a></li>
                    <li>{{ subcat.name.upper }}</li>
                </ul>
            </div>

        </div>

        <section class="catalog">
            <div class="container">
                <div class="catalog-wrapper">

                    <div class="catalog-filters block-w-r4">
                        <ul>
                            {% if param_filter %}
                                <li><a style="color: red" href="javascript:void(0);" onclick="del_filter();return false;"   >УБРАТЬ ФИЛЬТРЫ</a></li>
                            {% endif %}
                            <li><a href="javascript:void(0);" onclick="filter('{{ 'new' }}',{{ subcat.id }});return false;"  >НОВИНКИ</a></li>
                            {% for filter in subcat.filter_set.all %}
                                <li>  <a {% if filter.name_slug == param_filter %} class="filter-active" {% endif %}  href="javascript:void(0);" onclick="filter('{{ filter.name_slug }}',{{ subcat.id }});return false;"  >{{ filter.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="catalog-items">
                        <div class="catalog-items__filters block-w-r4 d-flex-center-between">
                            <div class="catalog-items__filters-left d-flex-center-between">
                                <span class="catalog-items__filters-button btn">Фильтры</span>
                                <p class="catalog-items__filters-label">В категории {{ items_count }} товаров</p>
                                <p class="catalog-items__filters-sort-label">Сортировать по:</p>
                            </div>
                            <div class="catalog-items__filters-right">
                                <div class="dropdown">
                                    <button onclick="customDropDown(this)" data-target="category" class="dropbtn">
                                        {% if param_order == '-created_at' %}НОВИЗНЕ{% endif %}
                                        {% if param_order == 'name' %}А - Я{% endif %}
                                        {% if param_order == '-name' %}Я - A{% endif %}
                                        {% if param_order == 'price' %}Цене &#8593;{% endif %}
                                        {% if param_order == '-price' %}Цене &#8595;{% endif %}
                                        {% if param_order == '-discount' %}скидке{% endif %}

                                    </button>
                                    <div id="category" class="dropdown-content">
                                        <a {% if param_order == '-created_at' %}class="active"{% endif %} onclick="order('-created_at',{{ subcat.id }});return false;">НОВИЗНЕ</a>
                                        <a {% if param_order == 'name' %}class="active"{% endif %} onclick="order('name',{{ subcat.id }});return false;">А - Я</a>
                                        <a {% if param_order == '-name' %}class="active"{% endif %} onclick="order('-name',{{ subcat.id }});return false;">Я - А</a>
                                        <a {% if param_order == 'price' %}class="active"{% endif %} onclick="order('price',{{ subcat.id }});return false;">Цене &#8593;</a>
                                        <a {% if param_order == '-price' %}class="active"{% endif %} onclick="order('-price',{{ subcat.id }});return false;">Цене &#8595;</a>
                                        <a {% if param_order == '-discount' %}class="active"{% endif %} onclick="order('-discount',{{ subcat.id }});return false;">скидке</a>
                                    </div>
                                </div>
                            </div>


                        </div>
                        <div class="catalog-items__inner">
                            {% for item in items %}
                                <div class="catalog-item block-w-r4">
                                    {% if item.is_new %}
                                        <span class="catalog-item__is-new">новинка</span>
                                    {% endif %}
                                    <span data-id="{{ item.id }}" style="cursor: pointer" class="catalog-item__in-fav  {% if item.id in wishlist_ids %} item-in-fav {% endif %} " @click="addInFav"></span>
                                    <a href="{% url 'item_page' item.name_slug %}" class="">
                                        <img class="catalog-item__image" src="{{ item.getfirstimage }}" alt="">
                                        <p class="catalog-item__article">АРТИКУЛ : {{ item.article }}</p>
                                        <p class="catalog-item__description">{{ item.name }}</p>
                                    </a>
                                    <div class="catalog-item-bottom ">
                                        <p class="catalog-item__price">{{ item.discount_value }}Р</p>
                                        <div class="catalog-item-bottom__in-cart">
                                            <input class="form-control" type="number" value="1" onkeyup="document.getElementById('add_btn_{{ item.id }}').dataset.num = this.value">
                                            <span id="add_btn_{{ item.id }}" data-id="{{ item.id }}" data-num="1" data-name="{{ item.name }}" data-price="{{ item.discount_value }}" data-image="{{ item.itemimage_set.first.image_small }}" @click="addItem"  ></span>
                                        </div>
                                    </div>
                                </div><!--//catalog-item -->
                            {% endfor %}

                        </div>
                        <nav style="margin-bottom: 30px" id="items_paginator" class="shop-pagination" aria-label="Shop navigation">
                            <ul class="pagination justify-content-end">
                                {% if items.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" href="?{% if param_search %}&search={{ param_search }}{% endif %}{% if param_filter %}&filter={{ param_filter }}{% endif %}{% if param_order %}&order={{ param_order }}{% endif %}{% if param_count %}&count={{ param_count }}{% endif %}" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                                {% for pg in items.paginator.page_range %}
                                    {% if items.number == pg %}
                                        <li class="page-item active"><a class="page-link" href="?{% if pg > 1 %}page={{ pg }}{% endif %}{% if param_search %}&search={{ param_search }}{% endif %}{% if param_filter %}&filter={{ param_filter }}{% endif %}{% if param_order %}&order={{ param_order }}{% endif %}{% if param_count %}&count={{ param_count }}{% endif %}">{{pg}}</a></li>
                                    {% elif pg > items.number|add:'-6' and pg < items.number|add:'6' %}
                                        <li class="page-item"><a class="page-link" href="?{% if pg > 1 %}page={{ pg }}{% endif %}{% if param_search %}&search={{ param_search }}{% endif %}{% if param_filter %}&filter={{ param_filter }}{% endif %}{% if param_order %}&order={{ param_order }}{% endif %}{% if param_count %}&count={{ param_count }}{% endif %}">{{pg}}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if items.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ items.paginator.num_pages }}{% if param_search %}&search={{ param_search }}{% endif %}{% if param_filter %}&filter={{ param_filter }}{% endif %}{% if param_order %}&order={{ param_order }}{% endif %}{% if param_count %}&count={{ param_count }}{% endif %}" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                {% endif %}
                            </ul>
                        </nav>
                        {% if seoText %}
                            {{ seoText | safe }}
                        {% else %}
                            {{ subcat.description|safe }}
                        {% endif %}

                    </div>

                </div>

            </div>

        </section>



    </div>

{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        let last_open=''
        let filter_button = document.getElementsByClassName('catalog-items__filters-button')[0]
        let filter_menu = document.getElementsByClassName('catalog-filters')[0]

        filter_button.onclick = function () {


            filter_menu.classList.toggle('filters-active')
        }
        function customDropDown(el) {

            let target = el.dataset.target
            if (last_open !=''){
                if (last_open === target){
                    document.getElementById(target).classList.toggle("show");
                    last_open=target
                }else{
                    document.getElementById(last_open).classList.remove("show");
                    document.getElementById(target).classList.toggle("show");
                    last_open=target
                }


            }else{

                document.getElementById(target).classList.toggle("show");
                last_open=target
            }

        }

        // Close the dropdown if the user clicks outside of it
        window.onclick = function(event) {
            if (!event.target.matches('.dropbtn')) {
                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
    </script>
{% endblock %}