cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_cart, name='show_cart'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('delete_from_main_cart/', views.delete_from_main_cart, name='delete_from_main_cart'),
    path('use_promo/', views.use_promo, name='use_promo'),
    path('sort_filter/', views.sort_filter, name='sort_filter'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('delete_from_cart/', views.delete_from_cart, name='delete_from_cart'),
    path('wishlist_add/', views.wishlist_add, name='wishlist_add'),
    path('wishlist_delete/', views.wishlist_delete, name='wishlist_delete'),
    path('get_cart/', views.get_cart, name='get_cart'),
    path('add_to_fav/', views.add_to_fav, name='add_to_fav'),



    # path('login/', views.login, name='login'),
    # path('logout/', views.logout_page, name='logout'),
    # path('profile/<nickname_req>', views.profile, name='profile'),
    # path('del_message/', views.del_message, name='del_message'),
    # path('bonus_pack/', views.bonus_pack, name='bonus_pack'),
    # path('about_us/', views.about_us, name='about_us'),
    # path('rules/', views.rules, name='rules'),
    # path('add_to_player_balance/', views.add_to_player_balance, name='add_to_player_balance'),
    # path('about_bonus_pack/', views.about_bonus_pack, name='about_bonus_pack'),




    # path('statistic/', views.statistic, name='statistic'),

]

customuser/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('log_in/', views.log_in, name='log_in'),
   path('logout/', views.log_out, name='logout'),
   path('signup/', views.signup, name='signup'),
   path('restore/', views.restore, name='restore'),
   path('account/', views.account, name='account'),
   path('account/edit', views.account_edit, name='account_edit'),
   path('account/wishlist', views.wishlist, name='wishlist'),
   path('account/orders', views.orders, name='orders'),
   path('account/order/<order_code>', views.order, name='order'),



    # path('login/', views.login, name='login'),
    # path('logout/', views.logout_page, name='logout'),
    # path('profile/<nickname_req>', views.profile, name='profile'),
    # path('del_message/', views.del_message, name='del_message'),
    # path('bonus_pack/', views.bonus_pack, name='bonus_pack'),
    # path('about_us/', views.about_us, name='about_us'),
    # path('rules/', views.rules, name='rules'),
    # path('add_to_player_balance/', views.add_to_player_balance, name='add_to_player_balance'),
    # path('about_bonus_pack/', views.about_bonus_pack, name='about_bonus_pack'),




    # path('statistic/', views.statistic, name='statistic'),

]

laskshmi_vue/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# from page.views import customhandler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('item/', include('item.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('customuser.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from customuser.models import User, Guest
from item.models import Item, PromoCode
from django.utils.safestring import mark_safe

class Wishlist(models.Model):
    client = models.ForeignKey(User, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                               verbose_name='Клиент')
    item = models.ForeignKey(Item, blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Товар')

    def __str__(self):
        return 'Закладка клиента : %s ' % self.client.email

    class Meta:
        verbose_name = "Закладка клиента"
        verbose_name_plural = "Закладки клиентов"


class OrderStatus(models.Model):
    name = models.CharField('Статус для заказа', max_length=100, blank=False)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = "Статус для заказа"
        verbose_name_plural = "Статусы для заказов"

class OrderPayment(models.Model):
    name = models.CharField('Вариант оплаты заказа', max_length=100, blank=False)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = "Вариант оплаты заказа"
        verbose_name_plural = "Варианты оплаты заказов"

class OrderShipping(models.Model):
    name = models.CharField('Вариант доставки заказа', max_length=100, blank=False)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = "Вариант доставки заказа"
        verbose_name_plural = "Варианты доставки заказов"

class Order(models.Model):
    client = models.ForeignKey(User, blank=True, null=True, default=None, on_delete=models.CASCADE,
                               verbose_name='Заказ клиента')
    guest = models.ForeignKey(Guest, blank=True, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='Заказ гостя')
    promo_code = models.ForeignKey(PromoCode, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                              verbose_name='Использованный промо-код')
    status = models.ForeignKey(OrderStatus, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                              verbose_name='Статус заказа')
    payment = models.ForeignKey(OrderPayment, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                               verbose_name='Оплата заказа')
    shipping = models.ForeignKey(OrderShipping, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                                verbose_name='Доставка заказа')
    total_price = models.IntegerField('Общая стоимость заказа', default=0)
    total_price_with_code = models.DecimalField('Общая стоимость заказа с учетом промо-кода', decimal_places=2,
                                                max_digits=10, default=0)
    track_code = models.CharField('Трек код', max_length=50, blank=True, null=True)
    order_code = models.CharField('Код заказа', max_length=10, blank=True, null=True)
    is_complete = models.BooleanField('Заказ выполнен ?', default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        if self.client:
            if self.promo_code:
                return 'Заказ № %s. Создан : %s  . Клиент: %s . Сумма заказа : %s' % (
                self.id, self.created_at.strftime('%d-%m-%Y'), self.client.email, self.total_price_with_code)
            else:
                return 'Заказ № %s. Создан : %s  . Клиент: %s . Сумма заказа : %s' % (
                self.id, self.created_at.strftime('%d-%m-%Y'), self.client.email, self.total_price)
        if self.guest:
            if self.promo_code:
                return 'Заказ № %s. Создан : %s  . Гость: %s . Сумма заказа : %s' % (
                self.id, self.created_at.strftime('%d-%m-%Y'), self.guest.email, self.total_price_with_code)
            else:
                return 'Заказ № %s. Создан : %s  . Гость: %s . Сумма заказа : %s' % (
                self.id, self.created_at.strftime('%d-%m-%Y'), self.guest.email, self.total_price)


    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def created_tag(self):

        return mark_safe('<strong>{}</strong>'.format(self.created_at.strftime('%d-%m-%Y, %H:%M:%S')))

    created_tag.short_description = mark_safe('<strong>Дaта заказа</strong>')

    def save(self, *args, **kwargs):
        if self.promo_code:
            self.total_price_with_code = self.total_price - (self.total_price * self.promo_code.promo_discount / 100)
        else:
            self.total_price_with_code = self.total_price


        super(Order, self).save(*args, **kwargs)




class ItemsInOrder(models.Model):
    order = models.ForeignKey(Order, blank=False, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='В заказе')
    item = models.ForeignKey(Item, blank=False, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='Товар')
    number = models.IntegerField('Кол-во', blank=True, null=True, default=0)
    current_price = models.IntegerField('Цена за ед.', default=0)
    total_price = models.IntegerField('Общая стоимость', default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.item.discount > 0:
            self.current_price = self.item.price - (self.item.price * self.item.discount / 100)
        else:
            self.current_price = self.item.price
        self.total_price = self.number * self.current_price

        super(ItemsInOrder, self).save(*args, **kwargs)


    def __str__(self):
        return 'Товар : %s . В заказе № %s .' % (self.item.name, self.order.id)

    class Meta:
        verbose_name = "Товар в заказе"
        verbose_name_plural = "Товары в заказе"

    def getfirstimage(self):
        url = None
        for img in self.item.itemimage_set.all():
            if img.is_main:
                url = img.image_small
        return url

    def image_tag(self):
        # used in the admin site model as a "thumbnail"
        if self.getfirstimage():
            return mark_safe('<img src="{}" width="100" height="100" />'.format(self.getfirstimage()))
        else:
            return mark_safe('<span>НЕТ МИНИАТЮРЫ</span>')

    def name_tag(self):
        name = self.item.name
        return name

    def article_tag(self):
        name = self.item.article
        return name

    article_tag.short_description = 'Артикул'
    name_tag.short_description = 'Название товара'
    image_tag.short_description = 'Основная картинка'


def ItemsInOrder_post_save(sender,instance,**kwargs):
    try:
        order = instance.order
    except:
        order = None

    if order:
        order_total_price = 0
        all_items_in_order = ItemsInOrder.objects.filter(order=order)

        for item in all_items_in_order:
            order_total_price += item.total_price

        instance.order.total_price = order_total_price
        instance.order.save(force_update=True)


post_delete.connect(ItemsInOrder_post_save, sender=ItemsInOrder)
post_save.connect(ItemsInOrder_post_save, sender=ItemsInOrder)

customuser/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('email', 'name', 'phone', 'password1', 'password2', )

class UpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'name', 'family', 'otchestvo', 'country', 'city', 'post_code', 'phone', 'address', 'is_allow_email')

        error_messages = {
             'email': {
                 'unique': "Указанный адрес уже кем-то используется",
             },}

customuser/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from customuser.models import User
from django.http import JsonResponse, HttpResponseRedirect
from .forms import SignUpForm, UpdateForm
from order.models import Wishlist,Order
from django.core.mail import send_mail
from django.template.loader import render_to_string

def create_password():
    from random import choices
    import string
    password = ''.join(choices(string.ascii_uppercase + string.ascii_lowercase + string.digits, k=8))
    return password

def account(request):
    if request.user.is_authenticated:
        return render(request, 'customuser/account.html', locals())
    else:
        return HttpResponseRedirect('/')

def orders(request):
    if request.user.is_authenticated:
        orders = Order.objects.filter(client=request.user)
        return render(request, 'customuser/orders.html', locals())
    else:
        return HttpResponseRedirect('/')

def order(request, order_code):
    if request.user.is_authenticated:
        order = Order.objects.get(order_code=order_code)
        return render(request, 'customuser/order.html', locals())
    else:
        return HttpResponseRedirect('/')

def account_edit(request):

    client = request.user

    if request.POST:
        form = UpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            client.profile_ok = True
            client.save(force_update=True)

        return render(request, 'customuser/account_edit.html', locals())
    else:
        form = UpdateForm(instance=client)
        return render(request, 'customuser/account_edit.html', locals())


def wishlist(request):
    if request.user.is_authenticated:
        wish_list = Wishlist.objects.filter(client=request.user)
        print('wish_list',wish_list)
        return render(request, 'customuser/wishlist.html', locals())
    else:
        return HttpResponseRedirect('/')


def restore(request):
    return_dict = {}
    return_dict['result'] = False
    try:
        user = User.objects.get(email=request.POST.get('email'))
    except:
        user = None

    if user:
        new_password = create_password()
        user.set_password(new_password)
        user.save()
        return_dict['result'] = True
        msg_html = render_to_string('email/restore_passord.html', {'login': user.email, 'password': new_password})
        send_mail('Новый пароль на сайте LAKSHMI888', None, 'info@lakshmi888.ru', [user.email],
                  fail_silently=False, html_message=msg_html)
    return JsonResponse(return_dict)


def log_out(request):
    logout(request)
    return HttpResponseRedirect('/')


def log_in(request):
    return_dict = {}
    email = request.POST.get('email')
    password = request.POST.get('password')
    print(email)

    user = authenticate(email=email, password=password)
    print(user)
    if user is not None:
        if user.is_active:
            login(request, user)
            return_dict['result'] = 'success'
            return JsonResponse(return_dict)
        else:
            return_dict['result'] = 'inactive'
            return JsonResponse(return_dict)
    else:
        return_dict['result'] = 'invalid'
        return JsonResponse(return_dict)
    return_dict['result'] = 'denied'
    return JsonResponse(return_dict)


def signup(request):
    return_dict = {}
    if request.method == 'POST':
        n1 = int(request.POST.get('n1'))
        n2 = int(request.POST.get('n2'))
        answer = int(request.POST.get('answer'))
        if n1 + n2 == answer:
            print(request.POST)
            email = request.POST.get('email')
            name = request.POST.get('name')
            phone = request.POST.get('phone')
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            data = {'email': email, 'name': name, 'phone': phone, 'password2': password2, 'password1': password1}
            form = SignUpForm(data=data)
            if form.is_valid():
                user = form.save(commit=False)
                user.is_active = True
                user.save()
                print('User registred')
                msg_html = render_to_string('email/register.html', {'login': email, 'password': password1})
                send_mail('Регистрация на сайте LAKSHMI888', None, 'info@lakshmi888.ru', [email],
                          fail_silently=False, html_message=msg_html)
                print('Email sent to {} with pass {}'.format(email,password1))
                login(request, user)


                return_dict['result'] = 'success'
                return JsonResponse(return_dict)
            else:
                return_dict['result'] = form.errors
                print(return_dict)
                return JsonResponse(return_dict)
        else:
            return_dict['result'] = 'bad'
            return JsonResponse(return_dict)

    else:
            form = SignUpForm()
    return_dict['result'] = 'not post'
    return JsonResponse(return_dict)

order/views.py
from django.shortcuts import render

# Create your views here.

templates/customuser/account.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}

<div class="main">
    <div class="container">
        <div class="breadcrumbs">
            <ul>
                <li><a href="/">Главная</a></li>

                <li>Личный кабинет</li>
            </ul>
        </div>

    </div>
    <section class="lk">
        <div class="container">
            <div class="section-header"><h1>Личный кабинет</h1></div>
           <div class="lk-wrapper">
               <div style="min-width: 200px" class="lk-item">
                   <a href="{% url 'orders' %}">
                        <img src="{% static 'images/lk_icon1.png' %}" alt="">
                        <p>МОИ ЗАКАЗЫ</p>
                   </a>

               </div>
                <div style="min-width: 200px" class="lk-item">
                    <a href="{% url 'account_edit' %}">
                        <img src="{%  static 'images/lk_icon2.png' %}" alt="">
                   <p>ЛИЧНЫЕ ДАННЫЕ</p>
                    </a>

               </div>
                <div style="min-width: 200px" class="lk-item">
                    <a href="{% url 'wishlist' %}">
                       <img src="{%  static 'images/lk_icon3.png' %}" alt="">
                   <p>ИЗБРАННОЕ</p>
                    </a>

               </div>
           </div>
        </div>
    </section>

</div>

{% endblock %}

templates/customuser/account_edit.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}
<div class="main">
    <div class="container">
        <div class="breadcrumbs">
            <ul>
                <li><a href="/">Главная</a></li>
                <li><a href="{% url 'account' %}">Личный кабинет</a></li>
                <li>Личные данные</li>
            </ul>
        </div>

    </div>
    <section class="lk-profile">
        <div class="container">
            <div class="section-header"><h1>Личные данные</h1></div>
            <div class="profile block-w-r4">
                <p class="text-bold mb-30">ЗАПОЛНЕНИЕ ВСЕХ ПОЛЕЙ ОБЯЗАТЕЛЬНО ДЛЯ ФОРМИРОВАНИЯ ЗАКАЗА.</p>
{{ form.errors }}

                 <form class="lk-profile-form" action="{% url 'account_edit' %}" method="post">{% csrf_token %}
                    <div class="lk-profile-form-wrapper">
                        <div class="lk-profile-form-block ">

                            <label>Ваше имя <sup>*</sup></label>
                            <input required="required" name="{{ form.name.name }}" type="text" class="form-control"  placeholder="Ваше имя" value="{% if not client.name %}{% else %}{{ client.name }}{% endif %}">
                            <label>Ваша фамилия <sup>*</sup></label>
                            <input required="required" name="{{ form.family.name }}" type="text" class="form-control"  placeholder="Ваша фамилия" value="{% if not client.family %}{% else %}{{ client.family }}{% endif %}">
                             <label>Ваша отчество <sup>*</sup></label>
                            <input  name="{{ form.otchestvo.name }}" type="text" class="form-control"  placeholder="Ваше отчество" value="{% if not client.otchestvo %}{% else %}{{ client.otchestvo }}{% endif %}">
                             <label>Ваш E-Mail  <sup>*</sup></label>
                             <input type="email" required="required" name="{{ form.email.name }}" class="form-control"  placeholder="Ваш E-Mail" value="{{ client.email }}">
                             <label>Ваш телефон  <sup>*</sup></label>
                            <input type="tel" required="required" name="{{ form.phone.name }}" class="form-control"  placeholder="Ваш телефон" value="{% if not client.phone %}{% else %}{{ client.phone }}{% endif %}">


                        </div>
                        <div class="lk-profile-form-block">
                            <label>Страна <sup>*</sup></label>
                            <input type="tel" required="required" name="{{ form.country.name }}" class="form-control"  placeholder="Страна" value="{% if not client.country %}{% else %}{{ client.country }}{% endif %}">
                              <label>Город <sup>*</sup></label>
                            <input type="tel" required="required" name="{{ form.city.name }}" class="form-control"  placeholder="Город" value="{% if not client.city %}{% else %}{{ client.city }}{% endif %}">
                              <label>Индекс <sup>*</sup></label>
                            <input type="tel" required="required" name="{{ form.post_code.name }}" class="form-control"  placeholder="Индекс" value="{% if not client.post_code %}{% else %}{{ client.post_code }}{% endif %}">
                              <label>Адрес доставки <sup>*</sup></label>
                            <textarea required="required" name="{{ form.address.name }}" class="form-control" rows="5"  placeholder="Адрес доставки">{% if not client.address %}{% else %}{{ client.address }}{% endif %}</textarea>
                        </div>
                    </div>

                     <label class="custom-checkbox mb-30"> Я хочу получать E-Mail рассылку с предложениями и скидками
                           <input type="checkbox" {% if client.is_allow_email %}checked="checked"{% endif %}  name="{{ form.is_allow_email.name }}" id="is_allow_email" >
                          <span class="checkmark"></span>
                        </label>
                      <button type="submit" class="btn ">Сохранить</button>

                </form>

            </div>
        </div>
    </section>

</div>
{% endblock%}

templates/customuser/order.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}

<!DOCTYPE html>


<div class="container main-container headerOffset">
      <div class="row">
        <div class="breadcrumbDiv col-lg-12">
            <ul class="breadcrumb">
                <li><a href="/">ГЛАВНАЯ</a></li>
                <li><a href="{% url 'account' %}">ЛИЧНЫЙ КАБИНЕТ</a></li>
                 <li><a href="{% url 'orders' %}">ВАШИ ЗАКАЗЫ</a></li>
                <li class="active">ЗАКАЗ #{{ order.id }} ID:{{ order.order_code }}</li>
            </ul>
        </div>
    </div>



    <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-7">

            <div class="row userInfo">


                <div class="statusContent">


                    <div class="col-sm-12">
                        <div class=" statusTop">
                            <p><strong>Статус заказа:</strong> {% if order.status %}{{ order.status.name }}{% else %}Обработка{% endif %}</p>

                            <p><strong>Дата заказа:</strong> {{ order.created_at|date:"D, d M Y, H:i" }} </p>

                            <p><strong>Номер и ID заказа:</strong> #{{ order.id }} ID:{{ order.order_code }} </p>
                        </div>
                    </div>

                    <div class="col-sm-12 clearfix">
                        <div class="order-box">
                            <div class="order-box-header">

                                В заказе
                            </div>


                            <div class="order-box-content">
                                <div class="table-responsive">
                                    <table class="order-details-cart">
                                        <tbody>
                                        {% for item in order.itemsinorder_set.all %}
                                        <tr class="cartProduct">
                                            <td class="cartProductThumb" style="width:20%">
                                                <div><a href="{% url 'item_page' item.item.name_slug %}"> <img alt="img"
                                                        {% for image in item.item.itemimage_set.all %}
                                                            {% if image.is_main %}
                                                               src="{{ image.image_small }}
                                                            {% endif %}
                                                        {% endfor %}">
                                                </a>
                                                </div>
                                            </td>
                                            <td style="width:40%">
                                                <div class="miniCartDescription">
                                                    <h4><a href="{% url 'item_page' item.item.name_slug %}"> {{ item.item.name }} </a></h4>

                                                    {% if item.item.discount > 0 %}

                                                        <div class="price" style="padding-bottom: 5px;">
                                                         <span style="font-size: 20px;">
                                                             <span>{{ item.item.discount_value }} &#8381;</span>
                                                             <span class="old-price">{{ item.item.price }} &#8381;</span>
                                                         </span>
                                                        </div>
                                                    {% else %}
                                                        <div class="price" style="padding-bottom: 5px;"><span style="font-size: 20px;">{{ item.item.price }} &#8381;</span></div>
                                                    {% endif %}
                                                </div>
                                            </td>
                                            <td class="" style="width:10%"><a> X {{ item.number }} ед.</a></td>
                                            <td class="" style="width:15%"><span> {{ item.total_price }} &#8381;</span></td>

                                        </tr>
                                        {% endfor %}

                                        <tr class="cartTotalTr blank">
                                            <td class="" style="width:20%">
                                                <div></div>
                                            </td>
                                            <td style="width:40%"></td>
                                            <td class="" style="width:20%"></td>
                                            <td class="" style="width:15%"><span>  </span></td>

                                        </tr>

                                        <tr class="cartTotalTr">
                                            <td class="" style="width:20%">
                                                <div></div>
                                            </td>
                                            <td colspan="2" style="width:40%">Общая сумма</td>
                                            <td class="" style="width:15%"><span> {{ order.total_price }} &#8381;</span></td>

                                        </tr>
                                        <tr class="cartTotalTr">
                                            <td class="" style="width:20%">
                                                <div></div>
                                            </td>
                                            <td colspan="2" style="width:40%">Скидка по промо-коду</td>
                                            <td class="" style="width:15%"><span> {% if order.promo_code %}{{ order.promo_code.promo_discount }}{% else %}0{% endif %} %</span></td>

                                        </tr>

                                        <tr class="cartTotalTr">
                                            <td class="" style="width:20%">
                                                <div></div>
                                            </td>
                                            <td style="width:40%"></td>
                                            <td class="" style="width:20%">ИТОГО</td>
                                             {% if order.total_price_with_code %}
                                                  <td class="" style="width:15%"><span class="price"> {{ order.total_price_with_code }} &#8381;</span></td>

                                            {% else %}
                                                  <td class="" style="width:15%"><span class="price"> {{ order.total_price }} &#8381;</span></td>

                                            {% endif %}


                                        </tr>


                                        </tbody>
                                    </table>
                                </div>

                            </div>
                        </div>

                    </div>


                </div>


            </div>
            <!--/row end-->

        </div>
        <div class="col-lg-3 col-md-3 col-sm-5"></div>
    </div>
    <!--/row-->

    <div style="clear:both"></div>
</div>
<!-- /main-container -->

<div class="gap"></div>

{% endblock %}